
[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
auto-format = true
formatter = {command = "ruff", args = ["format", "--line-length", "88", "-"]}

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]
# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "gdscript"
language-servers = ["gdscript"]
language-id = "gdscript" 

[language-server.gdscript]
command = "nc"
args = ["127.0.0.1", "6005"]


